language: dvt-common
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  matrix:
    - DJANGO=2.2
    - DJANGO=3.0

install:
  - python -m pip install -r requires.txt
  - python -m pip install Django~=$DJANGO
  - python -m pip install codecov mypy django-stubs

script:
    - dvt-common -m coverage run manage.py test -v3
    - mypy --config-file=mypy.ini .

after_success: codecov
