language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  matrix:
    - DJANGO=2.2
    - DJANGO=3.0

install:
  - pip install -r requires.txt
  - pip install Django~=$DJANGO
  - pip install codecov mypy django-stubs

script:
    - python -m coverage run src/manage.py test -v3
    - cd src && mypy --config-file=../mypy.ini .

after_success: codecov
